project:
  type: website
  output-dir: docs
website:
  title: "Juan F. Lafuente Barquero"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: posts.qmd
        text: Blog
      - href: portfolio.qmd
        text: Graphics Portfolio

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    toc: true



