project:
  type: website

website:
  title: "Juan Lafuente-Barquero"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true



